/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatecriopreto.ProjetoRevisteiro.view;

/**
 *
 * @author raphaelmachado
 */
public class InternalFrameTela04 extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrameTela02
     */
    public InternalFrameTela04() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_subtitulo = new javax.swing.JLabel();
        jl_voltar = new javax.swing.JLabel();
        jb_voltar = new javax.swing.JButton();
        jl_logoflip = new javax.swing.JLabel();
        jl_titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jb_novo = new javax.swing.JButton();
        jb_editar = new javax.swing.JButton();
        jb_deletar = new javax.swing.JButton();
        jb_salvar = new javax.swing.JButton();
        jt_nome = new javax.swing.JTextField();
        jl_nome = new javax.swing.JLabel();
        jl_cliente = new javax.swing.JLabel();
        jc_cliente = new javax.swing.JComboBox();
        jt_edicao = new javax.swing.JTextField();
        jl_data = new javax.swing.JLabel();
        jt_data = new javax.swing.JTextField();
        jl_edicao = new javax.swing.JLabel();
        jl_imagem = new javax.swing.JLabel();
        jc_imagem = new javax.swing.JComboBox();
        jt_categoria = new javax.swing.JTextField();
        jl_categoria = new javax.swing.JLabel();
        jl_url = new javax.swing.JLabel();
        jt_url = new javax.swing.JTextField();
        jt_descricao = new javax.swing.JTextField();
        jl_descricao = new javax.swing.JLabel();
        jl_fundoamarelo = new javax.swing.JLabel();
        jl_fundobranco = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_subtitulo.setBackground(new java.awt.Color(204, 204, 204));
        jl_subtitulo.setFont(new java.awt.Font("Myriad Pro", 1, 30)); // NOI18N
        jl_subtitulo.setForeground(new java.awt.Color(204, 204, 204));
        jl_subtitulo.setText("cadastro de revista");
        jl_subtitulo.setPreferredSize(new java.awt.Dimension(100, 50));
        getContentPane().add(jl_subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 410, 50));

        jl_voltar.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        jl_voltar.setForeground(new java.awt.Color(153, 153, 153));
        jl_voltar.setText("voltar");
        getContentPane().add(jl_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jb_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/botao-voltar.png"))); // NOI18N
        jb_voltar.setBorderPainted(false);
        jb_voltar.setContentAreaFilled(false);
        jb_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jl_logoflip.setForeground(new java.awt.Color(249, 171, 24));
        jl_logoflip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/logo-revisteiro.png"))); // NOI18N
        getContentPane().add(jl_logoflip, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jl_titulo.setBackground(new java.awt.Color(204, 204, 204));
        jl_titulo.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 36)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(204, 204, 204));
        jl_titulo.setText("REVISTEIRO DIGITAL");
        jl_titulo.setPreferredSize(new java.awt.Dimension(100, 50));
        getContentPane().add(jl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 410, 50));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 101, 560, -1));

        jb_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/botao-novo.png"))); // NOI18N
        jb_novo.setBorderPainted(false);
        jb_novo.setContentAreaFilled(false);
        getContentPane().add(jb_novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 415, -1, -1));

        jb_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/botao-editar.png"))); // NOI18N
        jb_editar.setBorderPainted(false);
        jb_editar.setContentAreaFilled(false);
        jb_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_editarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 415, -1, 60));

        jb_deletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/botao-deletar.png"))); // NOI18N
        jb_deletar.setBorderPainted(false);
        jb_deletar.setContentAreaFilled(false);
        jb_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_deletarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_deletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 415, -1, 60));

        jb_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/botao-salvar.png"))); // NOI18N
        jb_salvar.setBorderPainted(false);
        jb_salvar.setContentAreaFilled(false);
        jb_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 415, -1, 60));

        jt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(jt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 165, 320, 40));

        jl_nome.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jl_nome.setForeground(new java.awt.Color(204, 204, 204));
        jl_nome.setText("Nome");
        getContentPane().add(jl_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 175, -1, -1));

        jl_cliente.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jl_cliente.setForeground(new java.awt.Color(204, 204, 204));
        jl_cliente.setText("Cliente");
        getContentPane().add(jl_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jc_cliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jc_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 205, 322, 25));

        jt_edicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_edicaoActionPerformed(evt);
            }
        });
        getContentPane().add(jt_edicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 90, 40));

        jl_data.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jl_data.setForeground(new java.awt.Color(204, 204, 204));
        jl_data.setText("Data");
        getContentPane().add(jl_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        jt_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_dataActionPerformed(evt);
            }
        });
        getContentPane().add(jt_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 130, 40));

        jl_edicao.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jl_edicao.setForeground(new java.awt.Color(204, 204, 204));
        jl_edicao.setText("Edição");
        getContentPane().add(jl_edicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 242, -1, -1));

        jl_imagem.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jl_imagem.setForeground(new java.awt.Color(204, 204, 204));
        jl_imagem.setText("Imagem");
        getContentPane().add(jl_imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 272, -1, -1));

        jc_imagem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jc_imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 271, 322, 25));

        jt_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_categoriaActionPerformed(evt);
            }
        });
        getContentPane().add(jt_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 295, 320, 40));

        jl_categoria.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jl_categoria.setForeground(new java.awt.Color(204, 204, 204));
        jl_categoria.setText("Categoria");
        getContentPane().add(jl_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 306, -1, -1));

        jl_url.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jl_url.setForeground(new java.awt.Color(204, 204, 204));
        jl_url.setText("Url");
        getContentPane().add(jl_url, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 343, -1, -1));

        jt_url.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_urlActionPerformed(evt);
            }
        });
        getContentPane().add(jt_url, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 333, 320, 40));

        jt_descricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_descricaoActionPerformed(evt);
            }
        });
        getContentPane().add(jt_descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 320, 40));

        jl_descricao.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jl_descricao.setForeground(new java.awt.Color(204, 204, 204));
        jl_descricao.setText("Descrição");
        getContentPane().add(jl_descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 377, -1, -1));

        jl_fundoamarelo.setBackground(new java.awt.Color(235, 196, 13));
        jl_fundoamarelo.setOpaque(true);
        getContentPane().add(jl_fundoamarelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 495, 810, 15));

        jl_fundobranco.setBackground(new java.awt.Color(255, 255, 255));
        jl_fundobranco.setOpaque(true);
        getContentPane().add(jl_fundobranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_editarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_editarActionPerformed

    private void jb_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_deletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_deletarActionPerformed

    private void jb_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvarActionPerformed

    private void jb_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_voltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jb_voltarActionPerformed

    private void jt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_nomeActionPerformed

    private void jt_edicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_edicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_edicaoActionPerformed

    private void jt_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_dataActionPerformed

    private void jt_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_categoriaActionPerformed

    private void jt_urlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_urlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_urlActionPerformed

    private void jt_descricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_descricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_descricaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jb_deletar;
    private javax.swing.JButton jb_editar;
    private javax.swing.JButton jb_novo;
    private javax.swing.JButton jb_salvar;
    private javax.swing.JButton jb_voltar;
    private javax.swing.JComboBox jc_cliente;
    private javax.swing.JComboBox jc_imagem;
    private javax.swing.JLabel jl_categoria;
    private javax.swing.JLabel jl_cliente;
    private javax.swing.JLabel jl_data;
    private javax.swing.JLabel jl_descricao;
    private javax.swing.JLabel jl_edicao;
    private javax.swing.JLabel jl_fundoamarelo;
    private javax.swing.JLabel jl_fundobranco;
    private javax.swing.JLabel jl_imagem;
    private javax.swing.JLabel jl_logoflip;
    private javax.swing.JLabel jl_nome;
    private javax.swing.JLabel jl_subtitulo;
    private javax.swing.JLabel jl_titulo;
    private javax.swing.JLabel jl_url;
    private javax.swing.JLabel jl_voltar;
    private javax.swing.JTextField jt_categoria;
    private javax.swing.JTextField jt_data;
    private javax.swing.JTextField jt_descricao;
    private javax.swing.JTextField jt_edicao;
    private javax.swing.JTextField jt_nome;
    private javax.swing.JTextField jt_url;
    // End of variables declaration//GEN-END:variables

    
}
