/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatecriopreto.ProjetoRevisteiro.view;

/**
 *
 * @author raphaelmachado
 */
public class InternalFrameTela06 extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrameTela02
     */
    public InternalFrameTela06() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_voltar = new javax.swing.JLabel();
        jb_voltar = new javax.swing.JButton();
        jl_subtitulo = new javax.swing.JLabel();
        jl_logoflip = new javax.swing.JLabel();
        jl_titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jb_novo = new javax.swing.JButton();
        jb_editar = new javax.swing.JButton();
        jb_deletar = new javax.swing.JButton();
        jb_salvar = new javax.swing.JButton();
        jt_senha = new javax.swing.JTextField();
        jl_confirmasenha = new javax.swing.JLabel();
        jl_login = new javax.swing.JLabel();
        jt_login = new javax.swing.JTextField();
        jt_cargo = new javax.swing.JTextField();
        jl_cargo = new javax.swing.JLabel();
        jt_nome = new javax.swing.JTextField();
        jl_nome = new javax.swing.JLabel();
        jl_fundoamarelo = new javax.swing.JLabel();
        jl_fundobranco = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_voltar.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        jl_voltar.setForeground(new java.awt.Color(153, 153, 153));
        jl_voltar.setText("voltar");
        getContentPane().add(jl_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jb_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/botao-voltar.png"))); // NOI18N
        jb_voltar.setBorderPainted(false);
        jb_voltar.setContentAreaFilled(false);
        jb_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jl_subtitulo.setBackground(new java.awt.Color(204, 204, 204));
        jl_subtitulo.setFont(new java.awt.Font("Myriad Pro", 1, 30)); // NOI18N
        jl_subtitulo.setForeground(new java.awt.Color(204, 204, 204));
        jl_subtitulo.setText("cadastro de usuário");
        jl_subtitulo.setPreferredSize(new java.awt.Dimension(100, 50));
        getContentPane().add(jl_subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 410, 50));

        jl_logoflip.setForeground(new java.awt.Color(249, 171, 24));
        jl_logoflip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/logo-revisteiro.png"))); // NOI18N
        getContentPane().add(jl_logoflip, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jl_titulo.setBackground(new java.awt.Color(204, 204, 204));
        jl_titulo.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 36)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(204, 204, 204));
        jl_titulo.setText("REVISTEIRO DIGITAL");
        jl_titulo.setPreferredSize(new java.awt.Dimension(100, 50));
        getContentPane().add(jl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 410, 50));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 101, 560, -1));

        jb_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/botao-novo.png"))); // NOI18N
        jb_novo.setBorderPainted(false);
        jb_novo.setContentAreaFilled(false);
        getContentPane().add(jb_novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        jb_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/botao-editar.png"))); // NOI18N
        jb_editar.setBorderPainted(false);
        jb_editar.setContentAreaFilled(false);
        jb_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_editarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, 60));

        jb_deletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/botao-deletar.png"))); // NOI18N
        jb_deletar.setBorderPainted(false);
        jb_deletar.setContentAreaFilled(false);
        jb_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_deletarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_deletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, 60));

        jb_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/botao-salvar.png"))); // NOI18N
        jb_salvar.setBorderPainted(false);
        jb_salvar.setContentAreaFilled(false);
        jb_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, 60));

        jt_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_senhaActionPerformed(evt);
            }
        });
        getContentPane().add(jt_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 320, 40));

        jl_confirmasenha.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jl_confirmasenha.setForeground(new java.awt.Color(204, 204, 204));
        jl_confirmasenha.setText("Senha");
        getContentPane().add(jl_confirmasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 315, -1, -1));

        jl_login.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jl_login.setForeground(new java.awt.Color(204, 204, 204));
        jl_login.setText("Login");
        getContentPane().add(jl_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 275, -1, -1));

        jt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_loginActionPerformed(evt);
            }
        });
        getContentPane().add(jt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 320, 40));

        jt_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_cargoActionPerformed(evt);
            }
        });
        getContentPane().add(jt_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 320, 40));

        jl_cargo.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jl_cargo.setForeground(new java.awt.Color(204, 204, 204));
        jl_cargo.setText("Cargo");
        getContentPane().add(jl_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(jt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 320, 40));

        jl_nome.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jl_nome.setForeground(new java.awt.Color(204, 204, 204));
        jl_nome.setText("Nome");
        getContentPane().add(jl_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jl_fundoamarelo.setBackground(new java.awt.Color(235, 196, 13));
        jl_fundoamarelo.setOpaque(true);
        getContentPane().add(jl_fundoamarelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 495, 810, 15));

        jl_fundobranco.setBackground(new java.awt.Color(255, 255, 255));
        jl_fundobranco.setOpaque(true);
        getContentPane().add(jl_fundobranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_editarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_editarActionPerformed

    private void jb_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_deletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_deletarActionPerformed

    private void jb_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvarActionPerformed

    private void jb_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_voltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jb_voltarActionPerformed

    private void jt_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_senhaActionPerformed

    private void jt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_loginActionPerformed

    private void jt_cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_cargoActionPerformed

    private void jt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_nomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jb_deletar;
    private javax.swing.JButton jb_editar;
    private javax.swing.JButton jb_novo;
    private javax.swing.JButton jb_salvar;
    private javax.swing.JButton jb_voltar;
    private javax.swing.JLabel jl_cargo;
    private javax.swing.JLabel jl_confirmasenha;
    private javax.swing.JLabel jl_fundoamarelo;
    private javax.swing.JLabel jl_fundobranco;
    private javax.swing.JLabel jl_login;
    private javax.swing.JLabel jl_logoflip;
    private javax.swing.JLabel jl_nome;
    private javax.swing.JLabel jl_subtitulo;
    private javax.swing.JLabel jl_titulo;
    private javax.swing.JLabel jl_voltar;
    private javax.swing.JTextField jt_cargo;
    private javax.swing.JTextField jt_login;
    private javax.swing.JTextField jt_nome;
    private javax.swing.JTextField jt_senha;
    // End of variables declaration//GEN-END:variables

    
}
