/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatecriopreto.ProjetoRevisteiro.view;

/**
 *
 * @author raphaelmachado
 */
public class InternalFrameTela02 extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrameTela02
     */
    public InternalFrameTela02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_logoflip = new javax.swing.JLabel();
        jl_voltar = new javax.swing.JLabel();
        jb_voltar = new javax.swing.JButton();
        jl_titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jb_revistadestaque = new javax.swing.JButton();
        jl_titulorevista = new javax.swing.JLabel();
        jl_descricao = new javax.swing.JLabel();
        js_descricao = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jl_categoria = new javax.swing.JLabel();
        js_categoria = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jl_arquivo = new javax.swing.JLabel();
        js_arquivo = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jl_fundoamarelo = new javax.swing.JLabel();
        jl_fundobranco = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_logoflip.setForeground(new java.awt.Color(249, 171, 24));
        jl_logoflip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/logo-revisteiro.png"))); // NOI18N
        getContentPane().add(jl_logoflip, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jl_voltar.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        jl_voltar.setForeground(new java.awt.Color(153, 153, 153));
        jl_voltar.setText("voltar");
        getContentPane().add(jl_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jb_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/botao-voltar.png"))); // NOI18N
        jb_voltar.setBorderPainted(false);
        jb_voltar.setContentAreaFilled(false);
        jb_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jl_titulo.setBackground(new java.awt.Color(204, 204, 204));
        jl_titulo.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 36)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(204, 204, 204));
        jl_titulo.setText("REVISTEIRO DIGITAL");
        jl_titulo.setPreferredSize(new java.awt.Dimension(100, 50));
        getContentPane().add(jl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 410, 50));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 101, 560, -1));

        jb_revistadestaque.setBackground(new java.awt.Color(0, 0, 0));
        jb_revistadestaque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/revista4.png"))); // NOI18N
        jb_revistadestaque.setBorderPainted(false);
        jb_revistadestaque.setContentAreaFilled(false);
        jb_revistadestaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_revistadestaqueActionPerformed(evt);
            }
        });
        getContentPane().add(jb_revistadestaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 145, 146, 209));

        jl_titulorevista.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jl_titulorevista.setForeground(new java.awt.Color(153, 153, 153));
        jl_titulorevista.setText("ims health");
        getContentPane().add(jl_titulorevista, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jl_descricao.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        jl_descricao.setForeground(new java.awt.Color(153, 153, 153));
        jl_descricao.setText("edição_01");
        getContentPane().add(jl_descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, 30));

        jTextPane2.setEditable(false);
        jTextPane2.setBackground(new java.awt.Color(238, 238, 238));
        jTextPane2.setBorder(null);
        jTextPane2.setFont(new java.awt.Font("Helvetica", 0, 15)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(102, 102, 102));
        jTextPane2.setText("Desde 1969 no Brasil, a IMS Health é lider global em informações, tecnologia e serviços para a área da saúde, e oferece a seus clientes soluções completas para mensurar e impulsionar sua performance.");
        jTextPane2.setToolTipText("");
        jTextPane2.setAutoscrolls(false);
        jTextPane2.setOpaque(false);
        js_descricao.setViewportView(jTextPane2);

        getContentPane().add(js_descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 207, 130));

        jl_categoria.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        jl_categoria.setForeground(new java.awt.Color(153, 153, 153));
        jl_categoria.setText("Categoria");
        getContentPane().add(jl_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jTextPane3.setEditable(false);
        jTextPane3.setBackground(new java.awt.Color(238, 238, 238));
        jTextPane3.setBorder(null);
        jTextPane3.setFont(new java.awt.Font("Helvetica", 0, 15)); // NOI18N
        jTextPane3.setForeground(new java.awt.Color(102, 102, 102));
        jTextPane3.setText("Pesquisa, saúde, inovação ");
        jTextPane3.setToolTipText("");
        jTextPane3.setAutoscrolls(false);
        jTextPane3.setOpaque(false);
        js_categoria.setViewportView(jTextPane3);

        getContentPane().add(js_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 207, 30));

        jl_arquivo.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        jl_arquivo.setForeground(new java.awt.Color(153, 153, 153));
        jl_arquivo.setText("arquivo");
        getContentPane().add(jl_arquivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, 30));

        jList1.setFont(new java.awt.Font("Helvetica", 0, 15)); // NOI18N
        jList1.setForeground(new java.awt.Color(102, 102, 102));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "edição_01", "edição_02", "edição_03", "edição_04", "edição_05", "edição_06", "edição_09", "edição_10", "edição_12", "edição_13", "edição_14", "edição_15" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        js_arquivo.setViewportView(jList1);

        getContentPane().add(js_arquivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 155, 220));

        jl_fundoamarelo.setBackground(new java.awt.Color(235, 196, 13));
        jl_fundoamarelo.setOpaque(true);
        getContentPane().add(jl_fundoamarelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 495, 810, 15));

        jl_fundobranco.setBackground(new java.awt.Color(255, 255, 255));
        jl_fundobranco.setOpaque(true);
        getContentPane().add(jl_fundobranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_voltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jb_voltarActionPerformed

    private void jb_revistadestaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_revistadestaqueActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jb_revistadestaqueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JButton jb_revistadestaque;
    private javax.swing.JButton jb_voltar;
    private javax.swing.JLabel jl_arquivo;
    private javax.swing.JLabel jl_categoria;
    private javax.swing.JLabel jl_descricao;
    private javax.swing.JLabel jl_fundoamarelo;
    private javax.swing.JLabel jl_fundobranco;
    private javax.swing.JLabel jl_logoflip;
    private javax.swing.JLabel jl_titulo;
    private javax.swing.JLabel jl_titulorevista;
    private javax.swing.JLabel jl_voltar;
    private javax.swing.JScrollPane js_arquivo;
    private javax.swing.JScrollPane js_categoria;
    private javax.swing.JScrollPane js_descricao;
    // End of variables declaration//GEN-END:variables

    
}
