/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatecriopreto.ProjetoRevisteiro.view;

/**
 *
 * @author raphaelmachado
 */
public class InternalFrameTela07 extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrameTela02
     */
    public InternalFrameTela07() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tela021 = new br.edu.fatecriopreto.ProjetoRevisteiro.view.Tela02();
        jb_fechar = new javax.swing.JButton();
        jb_revista = new javax.swing.JButton();
        jb_sair = new javax.swing.JButton();
        jb_logocmn = new javax.swing.JLabel();
        jt_login = new javax.swing.JTextField();
        jp_senha = new javax.swing.JPasswordField();
        jl_fundoamarelo = new javax.swing.JLabel();
        jl_fundobranco = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/botao-fechar.png"))); // NOI18N
        jb_fechar.setToolTipText("Entrar");
        jb_fechar.setBorderPainted(false);
        jb_fechar.setContentAreaFilled(false);
        jb_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_fecharActionPerformed(evt);
            }
        });
        getContentPane().add(jb_fechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        jb_revista.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jb_revista.setForeground(new java.awt.Color(153, 153, 153));
        jb_revista.setText("Esqueceu a sua senha?");
        jb_revista.setBorderPainted(false);
        jb_revista.setContentAreaFilled(false);
        jb_revista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jb_revista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_revistaActionPerformed(evt);
            }
        });
        getContentPane().add(jb_revista, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jb_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/botao-entrar.png"))); // NOI18N
        jb_sair.setToolTipText("Entrar");
        jb_sair.setBorderPainted(false);
        jb_sair.setContentAreaFilled(false);
        jb_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_sairActionPerformed(evt);
            }
        });
        getContentPane().add(jb_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, -1, -1));

        jb_logocmn.setForeground(new java.awt.Color(249, 171, 24));
        jb_logocmn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/login-senha-cmn.png"))); // NOI18N
        getContentPane().add(jb_logocmn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, 390));

        jt_login.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jt_login.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_loginActionPerformed(evt);
            }
        });
        getContentPane().add(jt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 290, 55));

        jp_senha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jp_senha.setText("jPasswordField1");
        getContentPane().add(jp_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 290, 55));

        jl_fundoamarelo.setBackground(new java.awt.Color(235, 196, 13));
        jl_fundoamarelo.setOpaque(true);
        getContentPane().add(jl_fundoamarelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 810, 275));

        jl_fundobranco.setBackground(new java.awt.Color(255, 255, 255));
        jl_fundobranco.setOpaque(true);
        getContentPane().add(jl_fundobranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_loginActionPerformed

    private void jb_revistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_revistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_revistaActionPerformed

    private void jb_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_sairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_sairActionPerformed

    private void jb_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_fecharActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jb_fecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_fechar;
    private javax.swing.JLabel jb_logocmn;
    private javax.swing.JButton jb_revista;
    private javax.swing.JButton jb_sair;
    private javax.swing.JLabel jl_fundoamarelo;
    private javax.swing.JLabel jl_fundobranco;
    private javax.swing.JPasswordField jp_senha;
    private javax.swing.JTextField jt_login;
    private br.edu.fatecriopreto.ProjetoRevisteiro.view.Tela02 tela021;
    // End of variables declaration//GEN-END:variables

}
