/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.fatecriopreto.ProjetoRevisteiro.view;

/**
 *
 * @author raphaelmachadofreire
 */
public class Tela01 extends javax.swing.JFrame {

    /**
     * Creates new form Tela01
     */
    public Tela01() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_logoflip = new javax.swing.JLabel();
        jb_revista01 = new javax.swing.JButton();
        jb_revista02 = new javax.swing.JButton();
        jb_revista03 = new javax.swing.JButton();
        jb_revista04 = new javax.swing.JButton();
        jb_revista05 = new javax.swing.JButton();
        jb_revista06 = new javax.swing.JButton();
        jb_revista07 = new javax.swing.JButton();
        jb_revista08 = new javax.swing.JButton();
        jb_login = new javax.swing.JButton();
        jl_logocmn = new javax.swing.JLabel();
        jl_titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setAutoRequestFocus(false);

        jl_logoflip.setForeground(new java.awt.Color(249, 171, 24));
        jl_logoflip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/logo-revisteiro.png"))); // NOI18N

        jb_revista01.setBackground(new java.awt.Color(0, 0, 0));
        jb_revista01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/revista1.png"))); // NOI18N
        jb_revista01.setBorderPainted(false);
        jb_revista01.setContentAreaFilled(false);
        jb_revista01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_revista01ActionPerformed(evt);
            }
        });

        jb_revista02.setBackground(new java.awt.Color(0, 0, 0));
        jb_revista02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/revista2.png"))); // NOI18N
        jb_revista02.setBorderPainted(false);
        jb_revista02.setContentAreaFilled(false);
        jb_revista02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_revista02ActionPerformed(evt);
            }
        });

        jb_revista03.setBackground(new java.awt.Color(0, 0, 0));
        jb_revista03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/revista3.png"))); // NOI18N
        jb_revista03.setBorderPainted(false);
        jb_revista03.setContentAreaFilled(false);
        jb_revista03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_revista03ActionPerformed(evt);
            }
        });

        jb_revista04.setBackground(new java.awt.Color(0, 0, 0));
        jb_revista04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/revista4.png"))); // NOI18N
        jb_revista04.setBorderPainted(false);
        jb_revista04.setContentAreaFilled(false);
        jb_revista04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_revista04ActionPerformed(evt);
            }
        });

        jb_revista05.setBackground(new java.awt.Color(0, 0, 0));
        jb_revista05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/revista5.png"))); // NOI18N
        jb_revista05.setBorderPainted(false);
        jb_revista05.setContentAreaFilled(false);
        jb_revista05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_revista05ActionPerformed(evt);
            }
        });

        jb_revista06.setBackground(new java.awt.Color(0, 0, 0));
        jb_revista06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/revista6.png"))); // NOI18N
        jb_revista06.setBorderPainted(false);
        jb_revista06.setContentAreaFilled(false);
        jb_revista06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_revista06ActionPerformed(evt);
            }
        });

        jb_revista07.setBackground(new java.awt.Color(0, 0, 0));
        jb_revista07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/revista7.png"))); // NOI18N
        jb_revista07.setBorderPainted(false);
        jb_revista07.setContentAreaFilled(false);
        jb_revista07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_revista07ActionPerformed(evt);
            }
        });

        jb_revista08.setBackground(new java.awt.Color(0, 0, 0));
        jb_revista08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/revista8.png"))); // NOI18N
        jb_revista08.setBorderPainted(false);
        jb_revista08.setContentAreaFilled(false);
        jb_revista08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_revista08ActionPerformed(evt);
            }
        });

        jb_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/botao_admin.png"))); // NOI18N
        jb_login.setBorderPainted(false);

        jl_logocmn.setBackground(new java.awt.Color(0, 0, 0));
        jl_logocmn.setForeground(new java.awt.Color(255, 255, 255));
        jl_logocmn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/ProjetoRevisteiro/img/logo-cmn.png"))); // NOI18N

        jl_titulo.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 24)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(153, 153, 153));
        jl_titulo.setText("REVISTEIRO DIGITAL");
        jl_titulo.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_logocmn)
                    .addComponent(jl_logoflip))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_login))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jb_revista05, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_revista06, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_revista07, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_revista08, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb_revista01, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_revista02, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_revista03, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_revista04, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_logoflip)
                        .addGap(368, 368, 368)
                        .addComponent(jl_logocmn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_login))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_revista01, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_revista04, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_revista03, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_revista02, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_revista05, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_revista08, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_revista07, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_revista06, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_revista04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_revista04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_revista04ActionPerformed

    private void jb_revista01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_revista01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_revista01ActionPerformed

    private void jb_revista03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_revista03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_revista03ActionPerformed

    private void jb_revista02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_revista02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_revista02ActionPerformed

    private void jb_revista08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_revista08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_revista08ActionPerformed

    private void jb_revista07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_revista07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_revista07ActionPerformed

    private void jb_revista06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_revista06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_revista06ActionPerformed

    private void jb_revista05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_revista05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_revista05ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jb_login;
    private javax.swing.JButton jb_revista01;
    private javax.swing.JButton jb_revista02;
    private javax.swing.JButton jb_revista03;
    private javax.swing.JButton jb_revista04;
    private javax.swing.JButton jb_revista05;
    private javax.swing.JButton jb_revista06;
    private javax.swing.JButton jb_revista07;
    private javax.swing.JButton jb_revista08;
    private javax.swing.JLabel jl_logocmn;
    private javax.swing.JLabel jl_logoflip;
    private javax.swing.JLabel jl_titulo;
    // End of variables declaration//GEN-END:variables
}
